### ISSUE TITLE
Error shown but cannot find where it's being thrown

### ISSUE THREAD

**Issue by tgmerritt** [nanoexpress/pro#27]
When I use express - app starts on port 8080 as I designate and runs.

I trade out express for nanoexpress and I see:

```
git:(nanoexpress) ✗ node --trace-uncaught --trace-warnings server.js 
Text and data can only be passed by String, ArrayBuffer or TypedArray.
```

No other stack trace is emitted.  I have no idea how to track down this particular error.  

I'm going to guess that what this means is you cannot pass an argument to a function if that argument is not one of String, ArrayBuffer or TypedArray.  And if that's true, then I'm going to suppose that passing a JSON object as an argument to a function is what's causing this error:

`    let { token, expiresAtTimestamp } = setupTokenAndTimestamp(contextPayload);`

In the above - contextPayload here would be a JSON object.

If what I'm assuming is all correct, then I suppose this is not an issue with nanoexpress, but rather a feature request - because I can't use this server if it's not going to support JSON as arguments to functions.

**Comment by dalisoft** [comment]
Hi. 

- Are you really using Pro version?
- Without route code really hard to understand how and why this error occurs

See [this](https://github.com/uNetworking/uWebSockets.js/issues/276) please and make sure check your code again. 
Check examples, documentation and some tests before creating issue. 

I sure the error was occured because on your code something wrong. 
I am made library on top of uWS and provide premium support only for Sponsors. 
I hope you understand me.
